# Generated by Django 5.2.15 on 2026-06-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('robots', models.CharField(blank=True, max_length=100)),
                ('canonical', models.CharField(blank=True, max_length=500)),
                ('og_image', models.CharField(blank=True, max_length=500)),
                ('extra_jsonld', models.JSONField(blank=True, default=list, help_text='List of JSON-LD objects.')),
                ('path', models.CharField(db_index=True, help_text='URL path, e.g. /about/', max_length=500)),
                ('site_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='Leave blank to apply to all sites.', null=True)),
                ('language', models.CharField(blank=True, help_text='Leave blank to apply to all languages.', max_length=10)),
            ],
            options={
                'verbose_name': 'SEO path rule',
                'verbose_name_plural': 'SEO path rules',
                'indexes': [models.Index(fields=['path', 'site_id'], name='seo_suite_s_path_55c641_idx')],
                'constraints': [models.UniqueConstraint(fields=('path', 'site_id', 'language'), name='seopath_unique_path_site_lang')],
            },
        ),
    ]
