# Generated by Django 5.2.15 on 2026-06-04 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('robots', models.CharField(blank=True, max_length=100)),
                ('canonical', models.CharField(blank=True, max_length=500)),
                ('og_image', models.CharField(blank=True, max_length=500)),
                ('extra_jsonld', models.JSONField(blank=True, default=list, help_text='List of JSON-LD objects.')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('site_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO object rule',
                'verbose_name_plural': 'SEO object rules',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_suite_s_content_d8cb7a_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'site_id', 'language'), name='seoobject_unique_object_site_lang')],
            },
        ),
    ]
