# Generated by Django 5.2.15 on 2026-06-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, editable=False, help_text='Per-site version number, assigned automatically.')),
                ('content', models.TextField(blank=True, help_text='The robots.txt body.')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='The version currently served.')),
                ('site_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='Leave blank to apply to all sites.', null=True)),
                ('label', models.CharField(blank=True, help_text="Short name, e.g. 'Block /staging'.", max_length=255)),
                ('note', models.TextField(blank=True, help_text='Why this change was made (shown in history).')),
                ('created_by', models.CharField(blank=True, help_text='Username of who created this version.', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='When this version was made live.', null=True)),
                ('active_marker', models.CharField(blank=True, editable=False, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'robots.txt version',
                'verbose_name_plural': 'robots.txt versions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site_id', 'is_active'], name='seo_suite_r_site_id_532db2_idx')],
                'constraints': [models.UniqueConstraint(fields=('active_marker',), name='seo_suite_robots_single_active_per_scope')],
            },
        ),
    ]
